on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
 
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Install NPM dependencies
      run: npm install
    - name: Minify CSS and JS files
      run: npm run build

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate
 
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
    - name: Run linter
      # Run Linter
      run: composer exec --verbose phpcs -- --standard=PSR12 app routes
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
    - name: Run test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      # Add Code Climate secret key
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: composer exec --verbose phpunit tests -- --coverage-clover storage/logs/clover.xml
        coverageLocations: ${{github.workplace}}/storage/logs/clover.xml:clover
        debug: true
